export const genresList = [
    { id: 1, genre: "Action" },
    { id: 2, genre: "Comedy" },
    { id: 3, genre: "Drama" },
    { id: 4, genre: "Fantasy" },
    { id: 5, genre: "Horror" },
    { id: 6, genre: "Crime" },
    { id: 7, genre: "Thriller" },
    { id: 8, genre: "Sci-Fi" },
    { id: 9, genre: "Romance" },
    { id: 10, genre: "Animation" },
    { id: 11, genre: "Documentary" },
    { id: 12, genre: "War"},
    { id: 13, genre: "Biography"},
    { id: 14, genre: "Musical", },
    { id: 15, genre: "Family", },
    { id: 16, genre: "Adventure" },
    { id: 17, genre: "History", },
    { id: 18, genre: "Sport", },
    { id: 19, genre: "Western", },
    { id: 20, genre: "Reality Show" },
    { id: 21, genre: "Talk Show" },
]